### ISSUE TITLE
ITDynamic abstract class issue

### ISSUE THREAD

**Issue by schulzrinne** [flack/quickform#10]
vendor/openpsa/quickform/lib/HTML/QuickForm/Renderer/ITDynamic.php:23 Class HTML_QuickForm_Renderer_ITDynamic contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods (HTML_QuickForm_Renderer::startForm, HTML_QuickForm_Renderer::renderHtml)

I added 

    public function startForm(&$form) {}
    public function renderHtml(&$data) {}

which seems to fix the problem, but this is probably not the right fix.

**Comment by flack** [comment]
@schulzrinne I think what yout proposed is exactly the right fix, since it restores the behavior of the old PEAR QuickForm. Committed & Pushed, thx for the report!
