### ISSUE TITLE
Syntax Error in HTML/QuickForm/date.php in latest version

### ISSUE THREAD

**Issue by retry** [flack/quickform#11]
Missing a ) for the array_walk() in the 2nd change:

                        array_walk($options, function(&$v, $k) {
                            $v = intval($v);
                        };

That last line should be:
                        });

Sorry I cannot figure out how this markdown formatting is supposed to work. It's line 350 in date.php

**Comment by retry** [comment]
My pleasure.  Thanks for maintaining this and ensuring it's php7.2 ready.  I'm still on 7.1 myself, but it's one less headache to worry about when trying to ensure my code works on the next jump.

BTW, it's not essential, but do you think you could get rid of all the ?> tags and the end of all files? These are just unnecessary liabilities if an errant whitespace is ever introduced.  You removed the one from the ITDyamic.php file but not others that were changed in this rev.

Right now every file ends with ?> except for these two I believe:
./QuickForm/Error.php
./QuickForm/Renderer/ITDynamic.php

**Comment by flack** [comment]
Sure, can't hurt. I've removed the closing `?>` tags (an fixed the wrong encoding in `HTML_Common`)

**Comment by retry** [comment]
You're the man!
