### ISSUE TITLE
"date" element type unable to handle attributes passed in constructor

### ISSUE THREAD

**Issue by MaybeFactor** [flack/quickform#12]
When calling `addElement('date', 'whatever_date', 'Whatever', $options_array, $attributes)` I found that the resulting date element wasn't able to properly build itself later. 

I investigated and found that the `HTML_QuickForm_date` constructor passes its `$attributes` to the parent constructor's `$elements` argument, causing the internal `$_elements` to be non-empty when later inspected to decide whether to call createElements (i.e. since it is already non-empty, the group's elements must of been populated already, so no need to create them).

I tested a potential fix by just passing `null` instead of `$attributes` to the parent constructor, and that made it work as intended.

Note, I saw [this issue](https://github.com/flack/quickform/issues/7), which I believe is attempting to describe the same issue, but was not successfully communicated. In it, flack asked: 

> Can you paste an example where I can see what $options and $attributes look like?

flack, the reason your test didn't reveal the bug to you is that you are passing an empty array to the `$attributes` argument. If you populate the array with attributes, the bug should become apparent. e.g.
`$attributes = array('class' => 'this-is-a-class');
$form->addElement('date', 'whatever_date', 'Whatever', array(), $attributes);`

**Comment by flack** [comment]
fixed by #14
