### ISSUE TITLE
"Compare" validation rule fails to correctly compare string values

### ISSUE THREAD

**Issue by MaybeFactor** [flack/quickform#13]
The "Compare" validation rule converts values to float for === and !== operators, causing all string values to appear equal.

**Comment by flack** [comment]
In fact, all the conversion functions were accidentally reversed in this commit:

https://github.com/flack/quickform/commit/06b0e808323a4f02da2bd8c96cc8ea658cb10e9e#diff-99d4eace39da4758e49af9f0526a6163

So all the `floatval`s should be replaced by `strval` and vice versa

**Comment by flack** [comment]
fixed by #14
