### ISSUE TITLE
Composer release

### ISSUE THREAD

**Issue by yuxx** [flack/quickform#20]
Hi, thank you for marge my PR!
And I have more request.
I want to update from composer.
Please update composer package.
(Maybe tagging this master - e.g. v3.3.5.2 -, and release it.)

My project use [bear/saturday](https://github.com/bearsaturday/BEAR.Saturday) framework, and depends on this project.

**Comment by flack** [comment]
Hi!

alright, I've published a new release. If there's any issues let me know!
