### ISSUE TITLE
php7.0, 7.1

### ISSUE THREAD

**Issue by debianuser69** [flack/quickform#6]
Hi,

What is the status of this codebase working with php7?  Soon we will all have to migrate across the great chasm of legacy incompatibility.

**Comment by flack** [comment]
Hi,

I'm running it on 7.0 for about six months now without any problem, so it should work fine. Haven't tried 7.1 yet, but I don't think that will be much different

**Comment by debianuser69** [comment]
Ahh that's great to hear.  Thanks for letting me know.

**Comment by flack** [comment]
Closing for now. If you encounter any specific problem, just re-open (or create a new ticket)
