### ISSUE TITLE
$form->addElement('date', 'TheDate', 'Date', $options, $attributes) doesn't work

### ISSUE THREAD

**Issue by datapp** [flack/quickform#7]
In difference to the old QuickForm you can't use addElement with an array of attributes. You have to use 
$dateElement = new \HTML_QuickForm_date('TheDate', 'Date', $options);
$dateElement->setAttributes($attributes);
instead of:
$form->addElement('date', 'TheDate', 'Date', $options, $attributes);

Error log:
Fatal error: Call to a member function getName() on a non-object in /var/www/global/api/vendor/openpsa/quickform/lib/HTML/QuickForm/group.php on line 124

HTML_QuickForm->addElement( ) 
HTML_QuickForm_date->onQuickFormEvent( )        ../QuickForm.php:516
HTML_QuickForm_element->onQuickFormEvent( )     ../date.php:502
HTML_QuickForm_date->setValue( )        ../element.php:271
HTML_QuickForm_group->setValue( )       ../date.php:472

**Comment by flack** [comment]
I just tried to reproduce this locally with the following code:

```php
$form = new HTML_QuickForm();
$form->addElement('date', 'TheDate', 'Date', [], []);
```

but that works as expected and doesn't throw an error. Can you paste an example where I can see what `$options` and `$attributes` look like?
