### ISSUE TITLE
Renderer ArraySmarty broken

### ISSUE THREAD

**Issue by DerVO** [flack/quickform#9]
I use `HTML_QuickForm_Renderer_ArraySmarty` in my code and I noticed, that the output of this changed compared to my Quickform PEAR installation.

Instead of having:

```
Array (
 [frozen]       => whether the complete form is frozen'
 ...
 [1st_element_name] => Array for the 1st element
 ...
 [nth_element_name] => Array for the nth element
)
```

i got:

```
Array(
  'frozen'           => 'whether the form is frozen',
  ...
  'elements' => array(
    element_1,
    ...
    element_N
  )
)
```

Problem is, that `HTML_QuickForm_Renderer_ArraySmarty` is deviated from `HTML_QuickForm_Renderer_Array` and in the parent we have some private methods, which the child tries to overload - but w/o success. So the `_storeArray` method from the parent is executed which leads to the unexpected output.

Please see my pull request #8 :)

**Comment by flack** [comment]
Fixed by #8

Thanks for reporting (and fixing :-))
